language: python
dist: xenial
cache: pip
python:
    # minimum required Python version
    - 3.6
    - 3.9
    - nightly
    - pypy3
install:
    - pip install -U 'setuptools>=18.5' 'pip>=6.0' 'wheel'
    # Need to install pyperformance,
    # pyperformance/tests/test_compare.py imports it
    - pip install -e .
script:
    - python runtests.py
