language: python
dist: xenial
cache: pip
python:
    - 2.7
    - 3.7
    - pypy
install:
    - pip install -U 'setuptools>=18.5' 'pip>=6.0'
    # Need to install performance, performance/tests/test_compare.py imports it
    - pip install -e .
script:
    - python runtests.py
